#cloud-config
# Add groups to the system
# empty group hashicorp.
groups:
  - admingroup: [root,sys]
  - hashicorp

package_upgrade: true

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: tf
    gecos: terraform user
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: true
    ssh_authorized_keys:
      - ${public_key}

packages:
  - go
  - docker
  - kubernetes-client

runcmd:
  - echo "hello world" > hello1.txt
  - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - sudo install minikube-linux-amd64 /usr/local/bin/minikube
  - sudo usermod -aG docker $USER
  - sudo systemctl start docker