#cloud-config
# Add groups to the system
# empty group hashicorp.
groups:
  - admingroup: [root,sys]
  - hashicorp
  - docker: [tf]

package_upgrade: true

# Add users to the system. Users are added after groups are added.
users:
  - default
  - name: tf
    gecos: terraform user
    shell: /bin/bash
    primary_group: hashicorp
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, docker
    lock_passwd: true
    ssh_authorized_keys:
      - ${public_key}

# ali linux hangs at yum install -t
# packages:
#   - golang
#   - docker
#   - kubernetes-client

runcmd:
  - cd /home/tf
  - echo "hello world" > hello1.txt
  - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - install minikube-linux-amd64 /usr/local/bin/minikube
  # docker-ce
  - yum install -y yum-utils
  - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  - yum install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  - usermod -aG docker $USER
  - systemctl start docker
  # kubectl
  - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  - install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl